-- Use this block from SYSTEM user
-- CREATE USER cop3710 IDENTIFIED BY "sp2026";
-- GRANT ALL PRIVILEGES TO cop3710;

-- Creating the Game Table, Stores Basic Information on the Game,
create table GAME(
    Game_ID int NOT NULL, -- Isn't coming with data by default, autogenerated.
    Game_Name varchar2(200) NOT NULL,
    Release_Year smallint,
    Publisher_Name varchar2(100) NOT NULL,

    CONSTRAINT PK_GAME PRIMARY KEY (Game_ID)
);

-- Creating the Game_Specs Table, Stores some more complex info on the games.
create table GAME_SPECS(
    Game_ID int NOT NULL,
    Game_Spec_ID int NOT NULL, -- Isn't coming with data by default, autogenerated.
    Genre_Name varchar2(25) NOT NULL,
    Launch_Price decimal(10,2) DEFAULT 0.0,
    Current_Price decimal(10,2) DEFAULT 0.0,

    CONSTRAINT PK_GAME_SPECS PRIMARY KEY (Game_ID, Game_Spec_ID),
    CONSTRAINT CK_LPrice CHECK(Launch_Price >= 0),
    CONSTRAINT CK_CPrice CHECK (Current_Price >= 0)
);

-- Allowing Game_Specs to reference Game_IDs from Game Table
ALTER TABLE GAME_SPECS
    ADD CONSTRAINT FK_GAME_SPECS_GAME_ID
    FOREIGN KEY (Game_ID)
    REFERENCES GAME(Game_ID);

-- Creating the Publisher Table, Stores information about different Publishers
create table PUBLISHER(
    Publisher_Name varchar2(100) NOT NULL,
    Founding_Year smallint,
    Total_Games int DEFAULT 0,

    CONSTRAINT PK_PUBLISHER PRIMARY KEY(Publisher_Name),
    CONSTRAINT CK_TGames CHECK (Total_Games >=0)
);

-- Allowing Game Table to reference Publisher_Name from Publishers Table
ALTER TABLE GAME
    ADD CONSTRAINT FK_GAME_PUBLISHER_NAME
    FOREIGN KEY (Publisher_Name)
    REFERENCES PUBLISHER(Publisher_Name);

-- Creating the Platform Table, Stores information about different platforms that games can be played on.
create table PLATFORMS(
    Platform_Name varchar2(50) NOT NULL,
    Platform_Holder varchar2(50),
    Launch_Year smallint,

    CONSTRAINT PK_PLATFORM PRIMARY KEY (Platform_Name)
);

-- Creating the Publisher_Platform Table, which acts as an associative table for Publisher and Platform.
create table PUBLISHER_PLATFORM(
    Publisher_Name varchar2(100) NOT NULL,
    Platform_Name varchar2(50) NOT NULL,
    Exclusive_Contract varchar2(1) NOT NULL,

    CONSTRAINT PK_PUBLISHER_PLATFORM PRIMARY KEY (Publisher_Name, Platform_Name)
);

-- Allowing Publisher_Platform to reference both Publisher_Name and Platform_Name from their respective tables.
ALTER TABLE PUBLISHER_PLATFORM
    ADD CONSTRAINT FK_PUB_PLAT_PUBN
    FOREIGN KEY (Publisher_Name)
    REFERENCES PUBLISHER(Publisher_Name);

ALTER TABLE PUBLISHER_PLATFORM
    ADD CONSTRAINT FK_PUB_PLAT_PLATN
    FOREIGN KEY (Platform_Name)
    REFERENCES PLATFORMS(Platform_Name);

-- Creating Game_Sales_Region, which would store each game's sales data from available regions
create table GAME_SALES_REGION(
    Game_ID int NOT NULL,
    Platform_Name varchar2(50) NOT NULL,
    Sales_Rank int NOT NULL,
    Region varchar2(20) NOT NULL,
    Region_Sales float NOT NULL,

    CONSTRAINT PK_GAME_SALES_REGION PRIMARY KEY (Game_ID, Platform_Name, Region)
);

-- Allowing Game_Sales_Region to reference Game_ID and Platform_Name from respective tables
ALTER TABLE GAME_SALES_REGION
    ADD CONSTRAINT FK_GAME_SALES_GAME_ID
    FOREIGN KEY (Game_ID)
    REFERENCES GAME(Game_ID);
ALTER TABLE GAME_SALES_REGION
    ADD CONSTRAINT FK_GAME_SALES_PLATFORM_N
    FOREIGN KEY (Platform_Name)
    REFERENCES PLATFORMS(Platform_Name);

-- SELECT * from PUBLISHER;


-- DROP TABLE GAME CASCADE CONSTRAINTS;
-- DROP TABLE GAME_SALES_REGION CASCADE CONSTRAINTS ;
-- DROP TABLE GAME_SPECS CASCADE CONSTRAINTS;
-- drop table PUBLISHER cascade constraints;
-- drop table PUBLISHER_PLATFORM cascade constraints;
-- drop table PLATFORMS cascade constraints;